-- Adds editable patient-level clinical notes for staff and hospital review.
-- Safe to run after the base schema and doctor/hospital migrations.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(80) PRIMARY KEY,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clinical_notes (
  note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  note_text TEXT NOT NULL,
  updated_by_role VARCHAR(30),
  updated_by_actor VARCHAR(80),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_clinical_notes_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_clinical_notes_updated ON clinical_notes(updated_at DESC);

ALTER TABLE clinical_notes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE clinical_notes FROM anon, authenticated;

INSERT INTO schema_migrations (version)
VALUES ('2026-06-16-clinical-notes')
ON CONFLICT (version) DO NOTHING;

COMMIT;
