-- Adds hospital registration and area-based emergency alert assignment.
-- Run this once on the hosted database before deploying the updated app.

BEGIN;

CREATE TABLE IF NOT EXISTS hospitals (
  hospital_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(30),
  service_area VARCHAR(120) NOT NULL,
  address TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hospital_auth (
  auth_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id INTEGER NOT NULL REFERENCES hospitals(hospital_id) ON DELETE CASCADE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_hospital_auth_hospital_id ON hospital_auth(hospital_id);

CREATE TABLE IF NOT EXISTS hospital_alert_assignments (
  assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id INTEGER NOT NULL REFERENCES emergency_alerts(alert_id) ON DELETE CASCADE,
  hospital_id INTEGER NOT NULL REFERENCES hospitals(hospital_id) ON DELETE CASCADE,
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(30) DEFAULT 'ASSIGNED',
  UNIQUE (alert_id, hospital_id)
);

CREATE INDEX IF NOT EXISTS idx_hospital_alert_assignments_hospital_id
  ON hospital_alert_assignments(hospital_id);

COMMIT;
