-- Production-leaning hardening layer for SmartHealth PostgreSQL/Supabase.
-- Safe to run after the base schema and watch-device migrations.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(80) PRIMARY KEY,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
  audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  actor_role VARCHAR(30),
  action VARCHAR(80) NOT NULL,
  target_type VARCHAR(80),
  target_id VARCHAR(80),
  outcome VARCHAR(30),
  detail TEXT,
  ip_address VARCHAR(80),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created ON audit_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor ON audit_events(actor_user_id, created_at DESC);

ALTER TABLE emergency_alerts
  ADD COLUMN IF NOT EXISTS lifecycle_status VARCHAR(30) DEFAULT 'CREATED';

CREATE TABLE IF NOT EXISTS alert_events (
  event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id INTEGER NOT NULL REFERENCES emergency_alerts(alert_id) ON DELETE CASCADE,
  from_status VARCHAR(30),
  to_status VARCHAR(30) NOT NULL,
  actor_role VARCHAR(30),
  actor_id VARCHAR(80),
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alert_events_alert ON alert_events(alert_id, created_at DESC);

CREATE TABLE IF NOT EXISTS patient_consents (
  consent_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  consent_type VARCHAR(60) NOT NULL,
  consent_version VARCHAR(30) NOT NULL,
  accepted BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_patient_consents_user_type ON patient_consents(user_id, consent_type, created_at DESC);

CREATE TABLE IF NOT EXISTS device_capabilities (
  capability_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE CASCADE,
  source VARCHAR(80),
  heart_rate_supported BOOLEAN DEFAULT FALSE,
  blood_pressure_supported BOOLEAN DEFAULT FALSE,
  sleep_temperature_supported BOOLEAN DEFAULT FALSE,
  sleep_temperature_trend_only BOOLEAN DEFAULT FALSE,
  activity_supported BOOLEAN DEFAULT FALSE,
  caveat TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_device_capabilities_device ON device_capabilities(device_id, updated_at DESC);

ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE alert_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_capabilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_migrations ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE audit_events FROM anon, authenticated;
REVOKE ALL ON TABLE alert_events FROM anon, authenticated;
REVOKE ALL ON TABLE patient_consents FROM anon, authenticated;
REVOKE ALL ON TABLE device_capabilities FROM anon, authenticated;
REVOKE ALL ON TABLE schema_migrations FROM anon, authenticated;

INSERT INTO schema_migrations (version)
VALUES ('2026-05-24-production-hardening')
ON CONFLICT (version) DO NOTHING;

COMMIT;
