-- Adds Galaxy Watch / Health Connect device tracking to an existing Supabase database.
-- Run this once before deploying backend code that writes device metadata.

BEGIN;

CREATE TABLE IF NOT EXISTS devices (
  device_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_type VARCHAR(30) NOT NULL,
  manufacturer VARCHAR(100),
  device_model VARCHAR(100),
  platform VARCHAR(50) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_device UNIQUE (user_id, platform, device_type, manufacturer, device_model)
);

CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);

ALTER TABLE temperature_readings
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_record_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pulse_readings
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_record_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE blood_pressure_readings
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_record_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE device_sync_events
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL;

COMMIT;
