-- PostgreSQL/Supabase schema for the Smart Health Monitor app.
-- Run this in the Supabase SQL Editor before deploying the Java web app.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(10),
  first_name VARCHAR(100) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  dob DATE,
  gender VARCHAR(20),
  marital_status VARCHAR(20),
  email VARCHAR(255) NOT NULL UNIQUE,
  cell_number VARCHAR(20),
  id_number VARCHAR(13),
  emergency_contact_name VARCHAR(150),
  emergency_contact_number VARCHAR(20),
  blood_group VARCHAR(10),
  known_allergies TEXT,
  chronic_conditions TEXT,
  address TEXT,
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS devices (
  device_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_type VARCHAR(30) NOT NULL,
  manufacturer VARCHAR(100),
  device_model VARCHAR(100),
  platform VARCHAR(50) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_device UNIQUE (user_id, platform, device_type, manufacturer, device_model)
);

CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);

CREATE TABLE IF NOT EXISTS user_auth (
  auth_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_auth_user_id ON user_auth(user_id);

CREATE TABLE IF NOT EXISTS patient_context_settings (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  sleep_start VARCHAR(5) NOT NULL,
  sleep_end VARCHAR(5) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS temperature_readings (
  temp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  temperature NUMERIC(4, 2) NOT NULL,
  status VARCHAR(20),
  source VARCHAR(50) DEFAULT 'MANUAL',
  external_record_id VARCHAR(100),
  measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_temperature_user_recorded
  ON temperature_readings(user_id, recorded_at DESC, temp_id DESC);

CREATE TABLE IF NOT EXISTS pulse_readings (
  pulse_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  bpm INTEGER NOT NULL,
  status VARCHAR(20),
  source VARCHAR(50) DEFAULT 'MANUAL',
  external_record_id VARCHAR(100),
  measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pulse_user_recorded
  ON pulse_readings(user_id, recorded_at DESC, pulse_id DESC);

CREATE TABLE IF NOT EXISTS blood_pressure_readings (
  bp_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  systolic INTEGER NOT NULL,
  diastolic INTEGER NOT NULL,
  status VARCHAR(20),
  source VARCHAR(50) DEFAULT 'MANUAL',
  external_record_id VARCHAR(100),
  measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_blood_pressure_user_recorded
  ON blood_pressure_readings(user_id, recorded_at DESC, bp_id DESC);

CREATE TABLE IF NOT EXISTS device_sync_events (
  sync_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  source_platform VARCHAR(50) NOT NULL,
  external_record_id VARCHAR(100),
  synced_for TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  sync_status VARCHAR(20) DEFAULT 'SYNCED'
);

CREATE INDEX IF NOT EXISTS idx_device_sync_user_id ON device_sync_events(user_id);

CREATE TABLE IF NOT EXISTS health_sync_sections (
  section_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  source VARCHAR(50) NOT NULL,
  window_start TIMESTAMP NOT NULL,
  window_end TIMESTAMP NOT NULL,
  heart_rate_latest INTEGER,
  heart_rate_min INTEGER,
  heart_rate_max INTEGER,
  heart_rate_average NUMERIC(6, 2),
  heart_rate_count INTEGER DEFAULT 0,
  temperature_latest NUMERIC(4, 2),
  temperature_min NUMERIC(4, 2),
  temperature_max NUMERIC(4, 2),
  temperature_average NUMERIC(4, 2),
  temperature_count INTEGER DEFAULT 0,
  systolic_latest INTEGER,
  diastolic_latest INTEGER,
  blood_pressure_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_health_sync_sections_user_window
  ON health_sync_sections(user_id, window_end DESC, section_id DESC);

CREATE TABLE IF NOT EXISTS emergency_alerts (
  alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bpm INTEGER,
  alert_status VARCHAR(20),
  countdown_seconds INTEGER DEFAULT 60,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_emergency_alert_user_id ON emergency_alerts(user_id);

CREATE TABLE IF NOT EXISTS ambulance_notifications (
  notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id INTEGER NOT NULL REFERENCES emergency_alerts(alert_id) ON DELETE CASCADE,
  sent_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  response_status VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_ambulance_alert_id ON ambulance_notifications(alert_id);

CREATE TABLE IF NOT EXISTS language_settings (
  language_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  language VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS voice_logs (
  voice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  command_text TEXT,
  command_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_voice_logs_user_id ON voice_logs(user_id);

CREATE TABLE IF NOT EXISTS health_advice (
  advice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advice_type VARCHAR(20),
  message TEXT
);

INSERT INTO health_advice (advice_type, message)
SELECT 'HIGH_TEMP', 'Drink water and monitor your temperature closely.'
WHERE NOT EXISTS (
  SELECT 1 FROM health_advice WHERE advice_type = 'HIGH_TEMP'
);

INSERT INTO health_advice (advice_type, message)
SELECT 'LOW_BPM', 'Seek medical help if the low pulse rate persists.'
WHERE NOT EXISTS (
  SELECT 1 FROM health_advice WHERE advice_type = 'LOW_BPM'
);

INSERT INTO health_advice (advice_type, message)
SELECT 'CRITICAL_BPM', 'Emergency services may be required immediately.'
WHERE NOT EXISTS (
  SELECT 1 FROM health_advice WHERE advice_type = 'CRITICAL_BPM'
);

ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_sync_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_context_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE devices FROM anon, authenticated;
REVOKE ALL ON TABLE health_sync_sections FROM anon, authenticated;
REVOKE ALL ON TABLE patient_context_settings FROM anon, authenticated;

COMMIT;
