-- Adds Galaxy Watch / Health Connect device tracking to an existing Supabase database.
-- Run this once before deploying backend code that writes device metadata.

BEGIN;

CREATE TABLE IF NOT EXISTS devices (
  device_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_type VARCHAR(30) NOT NULL,
  manufacturer VARCHAR(100),
  device_model VARCHAR(100),
  platform VARCHAR(50) NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_user_device UNIQUE (user_id, platform, device_type, manufacturer, device_model)
);

CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);

ALTER TABLE temperature_readings
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_record_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pulse_readings
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_record_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE blood_pressure_readings
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS external_record_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS measured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE device_sync_events
  ADD COLUMN IF NOT EXISTS device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS health_sync_sections (
  section_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER REFERENCES devices(device_id) ON DELETE SET NULL,
  source VARCHAR(50) NOT NULL,
  window_start TIMESTAMP NOT NULL,
  window_end TIMESTAMP NOT NULL,
  heart_rate_latest INTEGER,
  heart_rate_min INTEGER,
  heart_rate_max INTEGER,
  heart_rate_average NUMERIC(6, 2),
  heart_rate_count INTEGER DEFAULT 0,
  temperature_latest NUMERIC(4, 2),
  temperature_min NUMERIC(4, 2),
  temperature_max NUMERIC(4, 2),
  temperature_average NUMERIC(4, 2),
  temperature_count INTEGER DEFAULT 0,
  systolic_latest INTEGER,
  diastolic_latest INTEGER,
  blood_pressure_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_health_sync_sections_user_window
  ON health_sync_sections(user_id, window_end DESC, section_id DESC);

COMMIT;
