package za.ac.tut.util;

import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import za.ac.tut.model.PasswordUtils;

public final class PasswordResetService {

    private static final int OTP_MIN = 100000;
    private static final int OTP_RANGE = 900000;
    private static final long EXPIRY_MILLIS = 10L * 60L * 1000L;
    private static final int MAX_ATTEMPTS = 5;
    private static final SecureRandom RANDOM = new SecureRandom();

    private PasswordResetService() {
    }

    public static ResetRequestResult createOtp(Connection conn, String email) throws Exception {
        Integer userId = findUserId(conn, email);
        if (userId == null) {
            return ResetRequestResult.notFound();
        }

        expireExistingOtps(conn, userId);
        String otp = String.valueOf(OTP_MIN + RANDOM.nextInt(OTP_RANGE));
        Timestamp expiresAt = new Timestamp(System.currentTimeMillis() + EXPIRY_MILLIS);

        String sql = "INSERT INTO password_reset_otps (user_id, otp_hash, expires_at, attempt_count) "
                + "VALUES (?, ?, ?, 0)";
        try (PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, userId);
            ps.setString(2, PasswordUtils.hashPassword(otp));
            ps.setTimestamp(3, expiresAt);
            ps.executeUpdate();
        }

        return ResetRequestResult.created(otp);
    }

    public static ResetPasswordResult resetPassword(Connection conn, String email, String otp, String newPasswordHash)
            throws Exception {
        Integer userId = findUserId(conn, email);
        if (userId == null) {
            return ResetPasswordResult.invalid("Invalid or expired OTP.");
        }

        String sql = "SELECT reset_id, otp_hash, attempt_count FROM password_reset_otps "
                + "WHERE user_id = ? AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP "
                + "ORDER BY created_at DESC, reset_id DESC "
                + limitOne(conn);

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, userId);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return ResetPasswordResult.invalid("Invalid or expired OTP.");
                }

                int resetId = rs.getInt("reset_id");
                int attempts = rs.getInt("attempt_count");
                if (attempts >= MAX_ATTEMPTS) {
                    markUsed(conn, resetId);
                    return ResetPasswordResult.invalid("Too many OTP attempts. Request a new code.");
                }

                if (!PasswordUtils.verifyPassword(otp, rs.getString("otp_hash"))) {
                    incrementAttempts(conn, resetId);
                    return ResetPasswordResult.invalid("Invalid or expired OTP.");
                }

                updatePassword(conn, userId, newPasswordHash);
                markUsed(conn, resetId);
                return ResetPasswordResult.success();
            }
        }
    }

    public static boolean ensureSchema(Connection conn) {
        String sql = "CREATE TABLE IF NOT EXISTS password_reset_otps ("
                + "reset_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "user_id INTEGER NOT NULL, "
                + "otp_hash VARCHAR(255) NOT NULL, "
                + "expires_at TIMESTAMP NOT NULL, "
                + "used_at TIMESTAMP, "
                + "attempt_count INTEGER NOT NULL DEFAULT 0, "
                + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";

        if (DatabaseConfig.JDBC_URL.startsWith("jdbc:mariadb://")) {
            sql = "CREATE TABLE IF NOT EXISTS password_reset_otps ("
                    + "reset_id INT AUTO_INCREMENT PRIMARY KEY, "
                    + "user_id INT NOT NULL, "
                    + "otp_hash VARCHAR(255) NOT NULL, "
                    + "expires_at TIMESTAMP NOT NULL, "
                    + "used_at TIMESTAMP NULL, "
                    + "attempt_count INT NOT NULL DEFAULT 0, "
                    + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
        }

        try (Statement statement = conn.createStatement()) {
            statement.execute(sql);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private static Integer findUserId(Connection conn, String email) throws Exception {
        String sql = "SELECT id FROM users WHERE email = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, email);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt("id") : null;
            }
        }
    }

    private static String limitOne(Connection conn) throws Exception {
        String productName = conn.getMetaData().getDatabaseProductName();
        if (productName != null && productName.toLowerCase().contains("derby")) {
            return "FETCH FIRST 1 ROW ONLY";
        }
        return "LIMIT 1";
    }

    private static void expireExistingOtps(Connection conn, int userId) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE password_reset_otps SET used_at = CURRENT_TIMESTAMP WHERE user_id = ? AND used_at IS NULL")) {
            ps.setInt(1, userId);
            ps.executeUpdate();
        }
    }

    private static void incrementAttempts(Connection conn, int resetId) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE password_reset_otps SET attempt_count = attempt_count + 1 WHERE reset_id = ?")) {
            ps.setInt(1, resetId);
            ps.executeUpdate();
        }
    }

    private static void markUsed(Connection conn, int resetId) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE password_reset_otps SET used_at = CURRENT_TIMESTAMP WHERE reset_id = ?")) {
            ps.setInt(1, resetId);
            ps.executeUpdate();
        }
    }

    private static void updatePassword(Connection conn, int userId, String newPasswordHash) throws Exception {
        try (PreparedStatement ps = conn.prepareStatement(
                "UPDATE user_auth SET password_hash = ? WHERE user_id = ?")) {
            ps.setString(1, newPasswordHash);
            ps.setInt(2, userId);
            if (ps.executeUpdate() == 0) {
                try (PreparedStatement insert = conn.prepareStatement(
                        "INSERT INTO user_auth (user_id, password_hash) VALUES (?, ?)")) {
                    insert.setInt(1, userId);
                    insert.setString(2, newPasswordHash);
                    insert.executeUpdate();
                }
            }
        }
    }

    public static final class ResetRequestResult {
        private final boolean userFound;
        private final String otp;

        private ResetRequestResult(boolean userFound, String otp) {
            this.userFound = userFound;
            this.otp = otp;
        }

        static ResetRequestResult created(String otp) {
            return new ResetRequestResult(true, otp);
        }

        static ResetRequestResult notFound() {
            return new ResetRequestResult(false, null);
        }

        public boolean isUserFound() {
            return userFound;
        }

        public String getOtp() {
            return otp;
        }
    }

    public static final class ResetPasswordResult {
        private final boolean success;
        private final String message;

        private ResetPasswordResult(boolean success, String message) {
            this.success = success;
            this.message = message;
        }

        static ResetPasswordResult success() {
            return new ResetPasswordResult(true, "Password reset successfully. You can now sign in.");
        }

        static ResetPasswordResult invalid(String message) {
            return new ResetPasswordResult(false, message);
        }

        public boolean isSuccess() {
            return success;
        }

        public String getMessage() {
            return message;
        }
    }
}
